# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'VKApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VKApp

pod 'VK-ios-sdk'
pod 'Moya', '~> 13.0'

end
